export { FaSpotify } from 'react-icons/fa';
export { FcGoogle } from "react-icons/fc";

export {
    IoLogoInstagram,
    IoLogoGithub,
    IoDocumentTextOutline,
    IoAddOutline,
    IoGridOutline,
    IoPricetagsOutline,
    IoSearchOutline,
    IoMusicalNoteSharp,
    IoCartOutline,
    IoLogoGoogle,
    IoFilterOutline,
    IoTriangleOutline,
    IoKeyOutline,
    IoHomeOutline,
    IoLogoPaypal,
    IoPencil,
    IoCloseOutline,
    IoTrashOutline,
    IoSaveOutline,
    IoMailOutline,
    IoLockClosedOutline,
    IoEyeOutline,
    IoEyeOffOutline,
    IoCloudUploadOutline,
    IoCloudDownloadOutline,
    IoFolderOutline,
    IoCardOutline,
    IoImageOutline,
    IoCameraOutline,
    IoCodeOutline,
    IoExitOutline,
    IoLogoUsd,
    IoPersonAddOutline,
    IoPersonOutline,
    IoStarOutline,
    IoStarSharp,
    IoMenuOutline,
    IoPeopleOutline,
    IoMusicalNotesOutline,
    IoRefreshOutline,
    IoStatsChartOutline,
    IoShieldCheckmarkOutline,
    IoDownloadOutline,
    IoLaptopOutline,
    IoRibbonOutline,
    IoMoonOutline,
    IoSunnyOutline,
    IoGiftSharp
} from "react-icons/io5";