export { FaPlus, FaRegEye, FaMinus, FaFacebookF, FaCloudDownloadAlt, FaMoon, FaSpotify } from 'react-icons/fa';
export { FcGoogle } from 'react-icons/fc';
export { FiShoppingCart, FiUsers } from 'react-icons/fi';
export { IoMdSearch, IoIosMusicalNotes } from "react-icons/io";
export { IoDocumentText, IoSunny } from "react-icons/io5";
export { GrAdd } from 'react-icons/gr';
export { BiFilter, BiExit, BiPencil, BiGridAlt } from 'react-icons/bi';
export { MdOutlineChangeHistory, MdClose, MdLockOutline  } from 'react-icons/md';
export { BsKey, BsPaypal, BsInstagram } from 'react-icons/bs';
export { AiFillDelete, AiOutlineMail, AiOutlineHome, AiOutlineFolderOpen, AiOutlineArrowLeft, AiOutlineTags, AiOutlineCreditCard, AiOutlineCloudUpload, AiOutlineSave } from 'react-icons/ai';