export { FaSpotify } from 'react-icons/fa';
export { FcGoogle } from "react-icons/fc";
export {
    IoLogoInstagram,
    IoLogoGithub,
    IoDocumentTextOutline,
    IoSunnySharp,
    IoAddOutline,
    IoGridOutline,
    IoPricetagsOutline,
    IoSearchOutline,
    IoMusicalNoteSharp,
    IoCartOutline,
    IoLogoGoogle,
    IoFilterOutline,
    IoMoonSharp,
    IoTriangleOutline,
    IoKeyOutline,
    IoHomeOutline,
    IoLogoPaypal,
    IoPencil,
    IoCloseOutline,
    IoTrashOutline,
    IoSaveOutline,
    IoMailOutline,
    IoLockClosedOutline,
    IoEyeOutline,
    IoEyeOffOutline,
    IoCloudUploadOutline,
    IoCloudDownloadOutline,
    IoFolderOutline,
    IoCheckmarkOutline,
    IoCardOutline,
    IoImageOutline,
    IoCameraOutline,
    IoCodeOutline,
    IoExitOutline,
    IoLogoUsd,
    IoPersonAddOutline,
    IoPersonOutline,
    IoStarOutline,
    IoStarSharp
} from "react-icons/io5";